import fs from 'fs';
let content = fs.readFileSync('app/ChromaticPuzzle.jsx', 'utf8');

const newLevels = `
  { number: 126, name: "Trigger Core", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [["A", "B", "C", "D"], ["E", "F", "G", "H"], ["I", "J", "K", "L"]], pieces: ["OUT:RED|RED:RIGHT", "RED|BLUE:RIGHT", "BLUE|GREEN:RIGHT", "TRIGGER:GREEN:E|PINK:DOWN", "TRIGGER:PINK:F|YELLOW:RIGHT", "TRIGGER:YELLOW:G|CYAN:RIGHT", "TRIGGER:CYAN:H|PURPLE:RIGHT", "IN:PURPLE", "IN:RED", "PINK|RED:LEFT", "YELLOW|PINK:LEFT", "CYAN|YELLOW:LEFT"], solution: { A: "OUT:RED|RED:RIGHT", B: "RED|BLUE:RIGHT", C: "BLUE|GREEN:RIGHT", D: "TRIGGER:GREEN:E|PINK:DOWN", E: "TRIGGER:PINK:F|YELLOW:RIGHT", F: "TRIGGER:YELLOW:G|CYAN:RIGHT", G: "TRIGGER:CYAN:H|PURPLE:RIGHT", H: "IN:PURPLE", L: "IN:RED", K: "PINK|RED:LEFT", J: "YELLOW|PINK:LEFT", I: "CYAN|YELLOW:LEFT" }, hint: "Sequential unlocks!" },
  { number: 127, name: "Cascade Lock", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"], ["J", "K", "L"]], pieces: ["OUT:RED|RED:RIGHT,BLUE:DOWN", "TRIGGER:RED:D|GREEN:DOWN", "IN:BLUE", "TRIGGER:GREEN:G|PINK:RIGHT", "IN:PINK", "IN:YELLOW", "TRIGGER:BLUE:E|YELLOW:DOWN", "IN:PURPLE", "IN:CYAN", "TRIGGER:YELLOW:H|PURPLE:RIGHT", "TRIGGER:PURPLE:K|CYAN:RIGHT", "IN:ORANGE"], solution: { A: "OUT:RED|RED:RIGHT,BLUE:DOWN", B: "TRIGGER:RED:D|GREEN:DOWN", D: "TRIGGER:GREEN:G|PINK:RIGHT", G: "IN:PINK", C: "IN:BLUE", E: "TRIGGER:BLUE:E|YELLOW:DOWN", F: "IN:YELLOW", H: "TRIGGER:YELLOW:H|PURPLE:RIGHT", I: "IN:PURPLE", J: "IN:CYAN", K: "TRIGGER:PURPLE:K|CYAN:RIGHT", L: "IN:ORANGE" }, hint: "Multiple sources, multiple locks." },
  { number: 128, name: "Network Security", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [["A", "B", "C", "D"], ["E", "F", "G", "H"], ["I", "J", "K", "L"]], pieces: ["OUT:RED|RED:RIGHT", "TRIGGER:RED:C|BLUE:RIGHT", "TRIGGER:BLUE:G|GREEN:DOWN", "IN:GREEN", "IN:PINK", "TRIGGER:PINK:J|YELLOW:DOWN", "TRIGGER:YELLOW:K|CYAN:RIGHT", "IN:CYAN", "IN:ORANGE", "TRIGGER:ORANGE:B|PURPLE:UP", "TRIGGER:PURPLE:F|PINK:UP", "IN:RED"], solution: { A: "OUT:RED|RED:RIGHT", B: "TRIGGER:RED:C|BLUE:RIGHT", C: "TRIGGER:BLUE:G|GREEN:DOWN", G: "IN:GREEN", H: "IN:PINK", L: "TRIGGER:PINK:J|YELLOW:DOWN", K: "TRIGGER:YELLOW:K|CYAN:RIGHT", J: "IN:CYAN", I: "IN:ORANGE", E: "TRIGGER:ORANGE:B|PURPLE:UP", F: "TRIGGER:PURPLE:F|PINK:UP", D: "IN:RED" }, hint: "12 tiles of pure triggers." },
  { number: 129, name: "Shelf Ascend", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "STAIRS:UP:RED|BLUE:UP", "IN:BLUE", "IN:GREEN", "STAIRS:UP:BLUE|GREEN:UP", "IN:PURPLE", "STAIRS:UP:GREEN|PURPLE:UP", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED"], solution: { A: "OUT:RED|RED:RIGHT", B: "STAIRS:UP:RED|BLUE:UP", F: "STAIRS:UP:BLUE|GREEN:UP", J: "STAIRS:UP:GREEN|PURPLE:UP", I: "IN:PURPLE", E: "IN:BLUE", C: "IN:GREEN", D: "IN:PINK", G: "IN:YELLOW", H: "IN:CYAN", K: "IN:ORANGE", L: "IN:RED" }, hint: "Climb the shelves." },
  { number: 130, name: "Multi-Floor Maze", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "RED|BLUE:DOWN", "BLUE|GREEN:LEFT", "STAIRS:UP:GREEN|PURPLE:UP", "IN:PURPLE", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED", "IN:BLUE", "IN:GREEN"], solution: { A: "OUT:RED|RED:RIGHT", B: "RED|BLUE:DOWN", D: "BLUE|GREEN:LEFT", C: "STAIRS:UP:GREEN|PURPLE:UP", G: "IN:PURPLE", E: "IN:PINK", F: "IN:YELLOW", H: "IN:CYAN", I: "IN:ORANGE", J: "IN:RED", K: "IN:BLUE", L: "IN:GREEN" }, hint: "Navigate the maze across 3 floors." },
  { number: 131, name: "Shelf Pipeline", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "PIPE:LEFT:RED>RIGHT:BLUE", "STAIRS:UP:BLUE|GREEN:UP", "IN:GREEN", "IN:PURPLE", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED", "IN:BLUE", "IN:GREEN"], solution: { A: "OUT:RED|RED:RIGHT", B: "PIPE:LEFT:RED>RIGHT:BLUE", D: "STAIRS:UP:BLUE|GREEN:UP", H: "IN:GREEN", C: "IN:PURPLE", E: "IN:PINK", F: "IN:YELLOW", G: "IN:CYAN", I: "IN:ORANGE", J: "IN:RED", K: "IN:BLUE", L: "IN:GREEN" }, hint: "Pipes and shelves combined." },
  { number: 132, name: "Lock and Climb", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "TRIGGER:RED:E|BLUE:DOWN", "IN:BLUE", "STAIRS:UP:BLUE|GREEN:UP", "IN:GREEN", "IN:PURPLE", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED", "IN:BLUE"], solution: { A: "OUT:RED|RED:RIGHT", B: "TRIGGER:RED:E|BLUE:DOWN", D: "STAIRS:UP:BLUE|GREEN:UP", H: "IN:GREEN", C: "IN:BLUE", E: "IN:PURPLE", F: "IN:PINK", G: "IN:YELLOW", I: "IN:CYAN", J: "IN:ORANGE", K: "IN:RED", L: "IN:BLUE" }, hint: "Triggers that unlock upstairs paths." },
  { number: 133, name: "Cross-Floor Trigger", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "STAIRS:UP:RED|BLUE:UP", "TRIGGER:BLUE:I|GREEN:RIGHT", "IN:GREEN", "IN:PURPLE", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED", "IN:BLUE", "IN:GREEN"], solution: { A: "OUT:RED|RED:RIGHT", B: "STAIRS:UP:RED|BLUE:UP", F: "TRIGGER:BLUE:I|GREEN:RIGHT", E: "IN:GREEN", C: "IN:PURPLE", D: "IN:PINK", G: "IN:YELLOW", H: "IN:CYAN", I: "IN:ORANGE", J: "IN:RED", K: "IN:BLUE", L: "IN:GREEN" }, hint: "A trigger that affects a different floor." },
  { number: 134, name: "The Grand Opus", cells: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"], layout: [[["A", "B"], ["C", "D"]], [["E", "F"], ["G", "H"]], [["I", "J"], ["K", "L"]]], pieces: ["OUT:RED|RED:RIGHT", "PIPE:LEFT:RED>RIGHT:BLUE", "TRIGGER:BLUE:F|GREEN:DOWN", "STAIRS:UP:GREEN|PURPLE:UP", "IN:PURPLE", "IN:PINK", "IN:YELLOW", "IN:CYAN", "IN:ORANGE", "IN:RED", "IN:BLUE", "IN:GREEN"], solution: { A: "OUT:RED|RED:RIGHT", B: "PIPE:LEFT:RED>RIGHT:BLUE", D: "TRIGGER:BLUE:F|GREEN:DOWN", C: "STAIRS:UP:GREEN|PURPLE:UP", G: "IN:PURPLE", E: "IN:PINK", F: "IN:YELLOW", H: "IN:CYAN", I: "IN:ORANGE", J: "IN:RED", K: "IN:BLUE", L: "IN:GREEN" }, hint: "The ultimate challenge." },
`;

content = content.replace(
  /  { number: 125, name: "The Zenith", cells: \["A", "B", "C", "D", "E"\], layout: \[\["A", "B", "C", "D", "E"\]\], pieces: \["OUT:RED\|RED:RIGHT", "RED\|BLUE:RIGHT", "BLUE\|GREEN:RIGHT", "GREEN\|PURPLE:RIGHT", "IN:PURPLE"\], solution: { A: "OUT:RED\|RED:RIGHT", B: "RED\|BLUE:RIGHT", C: "BLUE\|GREEN:RIGHT", D: "GREEN\|PURPLE:RIGHT", E: "IN:PURPLE" }, hint: "The FINAL challenge before mastery." },/,
  `  { number: 125, name: "The Zenith", cells: ["A", "B", "C", "D", "E"], layout: [["A", "B", "C", "D", "E"]], pieces: ["OUT:RED|RED:RIGHT", "RED|BLUE:RIGHT", "BLUE|GREEN:RIGHT", "GREEN|PURPLE:RIGHT", "IN:PURPLE"], solution: { A: "OUT:RED|RED:RIGHT", B: "RED|BLUE:RIGHT", C: "BLUE|GREEN:RIGHT", D: "GREEN|PURPLE:RIGHT", E: "IN:PURPLE" }, hint: "The FINAL challenge before mastery." },\n${newLevels}`
);

// Update Victory Screen check
content = content.replace(/All 125 levels complete/g, "All 134 levels complete");

fs.writeFileSync('app/ChromaticPuzzle.jsx', content);
